In [2]:
import pandas as pd

In [ ]:
s1 = pd.Series()
s1

Series([], dtype: object)

In [ ]:
s2 = pd.Series([1,2,3,4,5])
s2

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [ ]:
s2.index

RangeIndex(start=0, stop=5, step=1)

In [ ]:
s2.values

array([1, 2, 3, 4, 5])

In [ ]:
s3 = pd.Series([1,2,3,4,5],index = [10,20,30,40,50])
s3

10    1
20    2
30    3
40    4
50    5
dtype: int64

In [ ]:
scores = pd.Series([3.2,4.5,2.6,3.5], index=['bob','george','alex','sarah'])
scores

bob       3.2
george    4.5
alex      2.6
sarah     3.5
dtype: float64

In [ ]:
scores.index

Index(['bob', 'george', 'alex', 'sarah'], dtype='object')

In [ ]:
scores.values

array([3.2, 4.5, 2.6, 3.5])

In [ ]:
d = {'bob':3.2, 'george':4.5, 'alex':2.6, 'sarah':3.5}

In [ ]:
s4 = pd.Series(d)
s4

bob       3.2
george    4.5
alex      2.6
sarah     3.5
dtype: float64

In [ ]:
s4.index

Index(['bob', 'george', 'alex', 'sarah'], dtype='object')

In [ ]:
s4.values

array([3.2, 4.5, 2.6, 3.5])

In [ ]:
df1 = pd.DataFrame()
type(df1)

pandas.core.frame.DataFrame

In [ ]:
print(df1)

Empty DataFrame
Columns: []
Index: []

In [ ]:
students_list = [['Bob','William',26,'Computer Eng',86],
                 ['Emma','Johnson',23,'Math',92],
                 ['Sarah', 'Smith',22,'Chems',95],
                 ['Alex','Brown',21, 'Electrical Eng',82]]
students_df = pd.DataFrame(students_list)
students_df

       0        1   2               3   4
0    Bob  William  26    Computer Eng  86
1   Emma  Johnson  23            Math  92
2  Sarah    Smith  22           Chems  95
3   Alex    Brown  21  Electrical Eng  82

In [ ]:
students_df = pd.DataFrame(students_list,columns=['First Name', 'Last Name', 'Age', 'Major', 'Score'])
students_df

  First Name Last Name  Age           Major  Score
0        Bob   William   26    Computer Eng     86
1       Emma   Johnson   23            Math     92
2      Sarah     Smith   22           Chems     95
3       Alex     Brown   21  Electrical Eng     82

In [ ]:
students_df = pd.DataFrame(students_list,columns=['First Name', 'Last Name', 'Age', 'Major', 'Score'],
                           index = ['bob@mail.com','emma@mail.com','sarah@mail.com','alex@mail.com'])
students_df

               First Name Last Name  Age           Major  Score
bob@mail.com          Bob   William   26    Computer Eng     86
emma@mail.com        Emma   Johnson   23            Math     92
sarah@mail.com      Sarah     Smith   22           Chems     95
alex@mail.com        Alex     Brown   21  Electrical Eng     82

In [ ]:
students_dict = { 'First name': ['Bob', 'Emma', 'Sarah', 'Alex'],
                  'Last name': ['William', 'Johnson', 'Smith','Brown'],
                  'Age': [26,23,22,21],
                  'Major': ['Computer Eng','Math','Chems','Electrical Eng'],
                  'Score': [86,92,95,82]
                  }

In [ ]:
students_df2 = pd.DataFrame(students_dict)
students_df2

  First name Last name  Age           Major  Score
0        Bob   William   26    Computer Eng     86
1       Emma   Johnson   23            Math     92
2      Sarah     Smith   22           Chems     95
3       Alex     Brown   21  Electrical Eng     82

In [ ]:
students_df2 = pd.DataFrame(students_dict, columns=['Last name', 'Score']) #pandas will show only these two attributes
students_df2

  Last name  Score
0   William     86
1   Johnson     92
2     Smith     95
3     Brown     82

In [1]:
students_df2 = pd.DataFrame(students_dict, columns=['Last name', 'Score', 'City']) #pandas will create new attribute with NaN data
students_df2

NameError: name 'pd' is not defined

In [ ]:
students_df.shape

(4, 5)

In [ ]:
students_df.head(2)

              First Name Last Name  Age         Major  Score
bob@mail.com         Bob   William   26  Computer Eng     86
emma@mail.com       Emma   Johnson   23          Math     92

In [ ]:
students_df.tail(2)

               First Name Last Name  Age           Major  Score
sarah@mail.com      Sarah     Smith   22           Chems     95
alex@mail.com        Alex     Brown   21  Electrical Eng     82

In [ ]:
students_df.info

<bound method DataFrame.info of                First Name Last Name  Age           Major  Score
bob@mail.com          Bob   William   26    Computer Eng     86
emma@mail.com        Emma   Johnson   23            Math     92
sarah@mail.com      Sarah     Smith   22           Chems     95
alex@mail.com        Alex     Brown   21  Electrical Eng     82>

In [ ]:
 students_df.describe()

             Age     Score
count   4.000000   4.00000
mean   23.000000  88.75000
std     2.160247   5.85235
min    21.000000  82.00000
25%    21.750000  85.00000
50%    22.500000  89.00000
75%    23.750000  92.75000
max    26.000000  95.00000

In [ ]:
df = pd.read_csv('data_new.csv')
df

     first_name last_name experience  score
0          Alex     Smith     Python     92
1         James     Jones        C++     97
2          Mary  Williams     Python     98
3      Patricia     Brown       Java     87
4      Jennifer    Taylor       HTML     88
5         Emily    Davies    Android     90
6       Michael    Wilson     Python     91
7       Jessica     Evans        C++     95
8          John    Thomas     Python     90
9        Thomas   Roberts       Java     89
10  Christopher    Martin     Python     83
11      Barbara       Lee        C++     86
12      Matthew  Anderson          R     97
13         Mark     White     Python     91
14        Nancy    Taylor       Java     96
15       Andrew     Smith          R     92

In [ ]:
df1 = pd.read_csv('data_new_01.csv',skiprows=1, names = ['a','b','c','d'])
df1

              a         b        c   d
0          Alex     Smith   Python  92
1         James     Jones      C++  97
2          Mary  Williams   Python  98
3      Patricia     Brown     Java  87
4      Jennifer    Taylor     HTML  88
5         Emily    Davies  Android  90
6       Michael    Wilson   Python  91
7       Jessica     Evans      C++  95
8          John    Thomas   Python  90
9        Thomas   Roberts     Java  89
10  Christopher    Martin   Python  83
11      Barbara       Lee      C++  86
12      Matthew  Anderson        R  97
13         Mark     White   Python  91
14        Nancy    Taylor     Java  96
15       Andrew     Smith        R  92

In [ ]:
df2 = pd.read_csv('data_new_02.csv',sep='|') #if seperator is diff. from ,
df2

     first_name last_name experience  score
0          Alex     Smith     Python     92
1         James     Jones        C++     97
2          Mary  Williams     Python     98
3      Patricia     Brown       Java     87
4      Jennifer    Taylor       HTML     88
5         Emily    Davies    Android     90
6       Michael    Wilson     Python     91
7       Jessica     Evans        C++     95
8          John    Thomas     Python     90
9        Thomas   Roberts       Java     89
10  Christopher    Martin     Python     83
11      Barbara       Lee        C++     86
12      Matthew  Anderson          R     97
13         Mark     White     Python     91
14        Nancy    Taylor       Java     96
15       Andrew     Smith          R     92

In [ ]:
df3 = pd.read_csv('data_new_03.csv',comment='#', sep='|') # to ignoring comments
df3

     first_name last_name experience  score
0          Alex     Smith     Python     92
1         James     Jones        C++     97
2          Mary  Williams     Python     98
3      Patricia     Brown       Java     87
4      Jennifer    Taylor       HTML     88
5         Emily    Davies    Android     90
6       Michael    Wilson     Python     91
7       Jessica     Evans        C++     95
8          John    Thomas     Python     90
9        Thomas   Roberts       Java     89
10  Christopher    Martin     Python     83
11      Barbara       Lee        C++     86
12      Matthew  Anderson          R     97
13         Mark     White     Python     91
14        Nancy    Taylor       Java     96
15       Andrew     Smith          R     92

In [ ]:
df3 = pd.read_csv('data_new_04.csv',skiprows=2, sep='|') #ignoring first 2 lines
df3

     first_name last_name experience  score
0          Alex     Smith     Python     92
1         James     Jones        C++     97
2          Mary  Williams     Python     98
3      Patricia     Brown       Java     87
4      Jennifer    Taylor       HTML     88
5         Emily    Davies    Android     90
6       Michael    Wilson     Python     91
7       Jessica     Evans        C++     95
8          John    Thomas     Python     90
9        Thomas   Roberts       Java     89
10  Christopher    Martin     Python     83
11      Barbara       Lee        C++     86
12      Matthew  Anderson          R     97
13         Mark     White     Python     91
14        Nancy    Taylor       Java     96
15       Andrew     Smith          R     92

In [ ]:
df5 = pd.read_csv('data_new_05.csv',header=None, sep='|') #no column names
df5

              0         1        2   3
0          Alex     Smith   Python  92
1         James     Jones      C++  97
2          Mary  Williams   Python  98
3      Patricia     Brown     Java  87
4      Jennifer    Taylor     HTML  88
5         Emily    Davies  Android  90
6       Michael    Wilson   Python  91
7       Jessica     Evans      C++  95
8          John    Thomas   Python  90
9        Thomas   Roberts     Java  89
10  Christopher    Martin   Python  83
11      Barbara       Lee      C++  86
12      Matthew  Anderson        R  97
13         Mark     White   Python  91
14        Nancy    Taylor     Java  96
15       Andrew     Smith        R  92

In [3]:
df = pd.read_csv('titanic.csv')

In [4]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [5]:
df.shape

(891, 12)

In [6]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [7]:
df.index

RangeIndex(start=0, stop=891, step=1)

In [9]:
ages = df['Age']
ages

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
886    27.0
887    19.0
888     NaN
889    26.0
890    32.0
Name: Age, Length: 891, dtype: float64

In [10]:
type(ages)

pandas.core.series.Series

In [11]:
ages.mean() #avg of ages

29.69911764705882

In [12]:
df[['Name','Age']]

                                                  Name   Age
0                              Braund, Mr. Owen Harris  22.0
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0
2                               Heikkinen, Miss. Laina  26.0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0
4                             Allen, Mr. William Henry  35.0
..                                                 ...   ...
886                              Montvila, Rev. Juozas  27.0
887                       Graham, Miss. Margaret Edith  19.0
888           Johnston, Miss. Catherine Helen "Carrie"   NaN
889                              Behr, Mr. Karl Howell  26.0
890                                Dooley, Mr. Patrick  32.0

[891 rows x 2 columns]

In [13]:
df.Age

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
886    27.0
887    19.0
888     NaN
889    26.0
890    32.0
Name: Age, Length: 891, dtype: float64

In [16]:
df.iloc[0,[1,4]]

Survived       0
Sex         male
Name: 0, dtype: object

In [17]:
df.loc[0,['Survived','Sex']]

Survived       0
Sex         male
Name: 0, dtype: object

In [18]:
df.iloc[:5,:3] #first 5 rows, first 3 columns

   PassengerId  Survived  Pclass
0            1         0       3
1            2         1       1
2            3         1       3
3            4         1       1
4            5         0       3

In [19]:
df.iloc[[0,-1],-3:] #first and last rows, last 3 columns

     Fare Cabin Embarked
0    7.25   NaN        S
890  7.75   NaN        Q

In [20]:
df.loc[5:10,'Name':'Ticket'] #row between 5 to 10, column between Name and Ticket

,Name,Sex,Age,SibSp,Parch,Ticket
5,"Moran, Mr. James",male,NaN,0,0,330877
6,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463
7,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909
8,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742
9,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736
10,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549

In [21]:
df.Sex == 'male'

0       True
1      False
2      False
3      False
4       True
       ...
886     True
887    False
888    False
889     True
890     True
Name: Sex, Length: 891, dtype: bool

In [22]:
df.loc[df.Sex == 'male']

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
883,884,0,2,"Banfield, Mr. Frederick James",male,28.0,0,0,C.A./SOTON 34068,10.5000,NaN,S
884,885,0,3,"Sutehall, Mr. Henry Jr",male,25.0,0,0,SOTON/OQ 392076,7.0500,NaN,S
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [23]:
df.loc[(df.Sex == 'female') & (df.Age > 35)] #females older than 35

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
15,16,1,2,"Hewlett, Mrs. (Mary D Kingcome)",female,55.0,0,0,248706,16.0000,NaN,S
25,26,1,3,"Asplund, Mrs. Carl Oscar (Selma Augusta Emilia...",female,38.0,1,5,347077,31.3875,NaN,S
40,41,0,3,"Ahlin, Mrs. Johan (Johanna Persdotter Larsson)",female,40.0,1,0,7546,9.4750,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
862,863,1,1,"Swift, Mrs. Frederick Joel (Margaret Welles Ba...",female,48.0,0,0,17466,25.9292,D17,S
865,866,1,2,"Bystrom, Mrs. (Karolina)",female,42.0,0,0,236852,13.0000,NaN,S
871,872,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,1,1,11751,52.5542,D35,S
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q

Data preprocessing

In [24]:
df.isna() # check if elements are NaN or not

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,False,False,False,False,False,False,False,False,False,False,True,False
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,True,False
3,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...
886,False,False,False,False,False,False,False,False,False,False,True,False
887,False,False,False,False,False,False,False,False,False,False,False,False
888,False,False,False,False,False,True,False,False,False,False,True,False
889,False,False,False,False,False,False,False,False,False,False,False,False
890,False,False,False,False,False,False,False,False,False,False,True,False

In [25]:
df.isna().any() #checks each attrb if has NaN value

PassengerId    False
Survived       False
Pclass         False
Name           False
Sex            False
Age             True
SibSp          False
Parch          False
Ticket         False
Fare           False
Cabin           True
Embarked        True
dtype: bool

In [26]:
df2 = df.dropna(axis=0) #drops all nan rows
df2

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
...,...,...,...,...,...,...,...,...,...,...,...,...
871,872,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,1,1,11751,52.5542,D35,S
872,873,0,1,"Carlsson, Mr. Frans Olof",male,33.0,0,0,695,5.0000,B51 B53 B55,S
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C

In [28]:
df.dropna(inplace=True) #drops all nan rows
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
...,...,...,...,...,...,...,...,...,...,...,...,...
871,872,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,1,1,11751,52.5542,D35,S
872,873,0,1,"Carlsson, Mr. Frans Olof",male,33.0,0,0,695,5.0000,B51 B53 B55,S
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C

In [29]:
df = pd.read_csv('titanic.csv')

In [30]:
df.fillna(0) #fill NaN values replaced with 0
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [37]:
df = pd.read_csv('titanic.csv')
df3 = df.fillna(df.mean(numeric_only=True)) #replacing NaN values with the means of these columns (only numeric ones)
df3

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.000000,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.000000,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.000000,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.000000,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.000000,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.000000,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.000000,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,29.699118,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.000000,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.000000,0,0,370376,7.7500,NaN,Q

In [38]:
df4 = df3.fillna(df3.mode().iloc[0]) #iloc is for getting the most frequent value
df4

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.000000,1,0,A/5 21171,7.2500,B96 B98,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.000000,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.000000,0,0,STON/O2. 3101282,7.9250,B96 B98,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.000000,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.000000,0,0,373450,8.0500,B96 B98,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.000000,0,0,211536,13.0000,B96 B98,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.000000,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,29.699118,1,2,W./C. 6607,23.4500,B96 B98,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.000000,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.000000,0,0,370376,7.7500,B96 B98,Q

In [40]:
df4.isna().any()

PassengerId    False
Survived       False
Pclass         False
Name           False
Sex            False
Age            False
SibSp          False
Parch          False
Ticket         False
Fare           False
Cabin          False
Embarked       False
dtype: bool

In [41]:
df.duplicated().any() #check duplicate rows

False

In [45]:
df = pd.read_csv('employees.csv')
df.columns

Index(['First Name', 'Gender', 'Start Date', 'Last Login Time', 'Salary',
       'Bonus %', 'Senior Management', 'Team'],
      dtype='object')

In [47]:
df.rename({'First Name':'First_Name', 'Start Date':'Start_Date', 'Last Login Time':'Last_Login_Time',
       'Bonus %':'Bonus', 'Senior Management':'Senior_Management'}) #will not change

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,8/6/1993,12:42 PM,97308,6.945,True,Marketing
1,Thomas,Male,3/31/1996,6:53 AM,61933,4.170,True,NaN
2,Maria,Female,4/23/1993,11:17 AM,130590,11.858,False,Finance
3,Jerry,Male,3/4/2005,1:00 PM,138705,9.340,True,Finance
4,Larry,Male,1/24/1998,4:47 PM,101004,1.389,True,Client Services
...,...,...,...,...,...,...,...,...
995,Henry,NaN,11/23/2014,6:09 AM,132483,16.655,False,Distribution
996,Phillip,Male,1/31/1984,6:30 AM,42392,19.675,False,Finance
997,Russell,Male,5/20/2013,12:39 PM,96914,1.421,False,Product
998,Larry,Male,4/20/2013,4:45 PM,60500,11.985,False,Business Development
999,Albert,Male,5/15/2012,6:24 PM,129949,10.169,True,Sales

In [49]:
df.rename({'First Name':'First_Name', 'Start Date':'Start_Date', 'Last Login Time':'Last_Login_Time',
       'Bonus %':'Bonus', 'Senior Management':'Senior_Management'},axis=1,inplace=True)
df

,First_Name,Gender,Start_Date,Last_Login_Time,Salary,Bonus,Senior_Management,Team
0,Douglas,Male,8/6/1993,12:42 PM,97308,6.945,True,Marketing
1,Thomas,Male,3/31/1996,6:53 AM,61933,4.170,True,NaN
2,Maria,Female,4/23/1993,11:17 AM,130590,11.858,False,Finance
3,Jerry,Male,3/4/2005,1:00 PM,138705,9.340,True,Finance
4,Larry,Male,1/24/1998,4:47 PM,101004,1.389,True,Client Services
...,...,...,...,...,...,...,...,...
995,Henry,NaN,11/23/2014,6:09 AM,132483,16.655,False,Distribution
996,Phillip,Male,1/31/1984,6:30 AM,42392,19.675,False,Finance
997,Russell,Male,5/20/2013,12:39 PM,96914,1.421,False,Product
998,Larry,Male,4/20/2013,4:45 PM,60500,11.985,False,Business Development
999,Albert,Male,5/15/2012,6:24 PM,129949,10.169,True,Sales

In [51]:
df['Bonus2'] = df.Bonus.round() #add new column
df

,First_Name,Gender,Start_Date,Last_Login_Time,Salary,Bonus,Senior_Management,Team,Bonus2
0,Douglas,Male,8/6/1993,12:42 PM,97308,6.945,True,Marketing,7.0
1,Thomas,Male,3/31/1996,6:53 AM,61933,4.170,True,NaN,4.0
2,Maria,Female,4/23/1993,11:17 AM,130590,11.858,False,Finance,12.0
3,Jerry,Male,3/4/2005,1:00 PM,138705,9.340,True,Finance,9.0
4,Larry,Male,1/24/1998,4:47 PM,101004,1.389,True,Client Services,1.0
...,...,...,...,...,...,...,...,...,...
995,Henry,NaN,11/23/2014,6:09 AM,132483,16.655,False,Distribution,17.0
996,Phillip,Male,1/31/1984,6:30 AM,42392,19.675,False,Finance,20.0
997,Russell,Male,5/20/2013,12:39 PM,96914,1.421,False,Product,1.0
998,Larry,Male,4/20/2013,4:45 PM,60500,11.985,False,Business Development,12.0
999,Albert,Male,5/15/2012,6:24 PM,129949,10.169,True,Sales,10.0

In [52]:
import numpy as np

In [54]:
df['random'] = pd.Series(np.random.randint(0,10,1000)) #add new column
df

,First_Name,Gender,Start_Date,Last_Login_Time,Salary,Bonus,Senior_Management,Team,Bonus2,random
0,Douglas,Male,8/6/1993,12:42 PM,97308,6.945,True,Marketing,7.0,9
1,Thomas,Male,3/31/1996,6:53 AM,61933,4.170,True,NaN,4.0,9
2,Maria,Female,4/23/1993,11:17 AM,130590,11.858,False,Finance,12.0,6
3,Jerry,Male,3/4/2005,1:00 PM,138705,9.340,True,Finance,9.0,7
4,Larry,Male,1/24/1998,4:47 PM,101004,1.389,True,Client Services,1.0,2
...,...,...,...,...,...,...,...,...,...,...
995,Henry,NaN,11/23/2014,6:09 AM,132483,16.655,False,Distribution,17.0,3
996,Phillip,Male,1/31/1984,6:30 AM,42392,19.675,False,Finance,20.0,6
997,Russell,Male,5/20/2013,12:39 PM,96914,1.421,False,Product,1.0,7
998,Larry,Male,4/20/2013,4:45 PM,60500,11.985,False,Business Development,12.0,5
999,Albert,Male,5/15/2012,6:24 PM,129949,10.169,True,Sales,10.0,2

In [55]:
df2 = df.iloc[:2]
df2

,First_Name,Gender,Start_Date,Last_Login_Time,Salary,Bonus,Senior_Management,Team,Bonus2,random
0,Douglas,Male,8/6/1993,12:42 PM,97308,6.945,True,Marketing,7.0,9
1,Thomas,Male,3/31/1996,6:53 AM,61933,4.170,True,NaN,4.0,9

In [57]:
df3 = pd.concat((df,df2),axis = 0) #adding df2 to df s end
df3

,First_Name,Gender,Start_Date,Last_Login_Time,Salary,Bonus,Senior_Management,Team,Bonus2,random
0,Douglas,Male,8/6/1993,12:42 PM,97308,6.945,True,Marketing,7.0,9
1,Thomas,Male,3/31/1996,6:53 AM,61933,4.170,True,NaN,4.0,9
2,Maria,Female,4/23/1993,11:17 AM,130590,11.858,False,Finance,12.0,6
3,Jerry,Male,3/4/2005,1:00 PM,138705,9.340,True,Finance,9.0,7
4,Larry,Male,1/24/1998,4:47 PM,101004,1.389,True,Client Services,1.0,2
...,...,...,...,...,...,...,...,...,...,...
997,Russell,Male,5/20/2013,12:39 PM,96914,1.421,False,Product,1.0,7
998,Larry,Male,4/20/2013,4:45 PM,60500,11.985,False,Business Development,12.0,5
999,Albert,Male,5/15/2012,6:24 PM,129949,10.169,True,Sales,10.0,2
0,Douglas,Male,8/6/1993,12:42 PM,97308,6.945,True,Marketing,7.0,9
1,Thomas,Male,3/31/1996,6:53 AM,61933,4.170,True,NaN,4.0,9

In [58]:
df3 = pd.concat((df,df2),axis = 0,ignore_index=True) #fixing the index
df3

,First_Name,Gender,Start_Date,Last_Login_Time,Salary,Bonus,Senior_Management,Team,Bonus2,random
0,Douglas,Male,8/6/1993,12:42 PM,97308,6.945,True,Marketing,7.0,9
1,Thomas,Male,3/31/1996,6:53 AM,61933,4.170,True,NaN,4.0,9
2,Maria,Female,4/23/1993,11:17 AM,130590,11.858,False,Finance,12.0,6
3,Jerry,Male,3/4/2005,1:00 PM,138705,9.340,True,Finance,9.0,7
4,Larry,Male,1/24/1998,4:47 PM,101004,1.389,True,Client Services,1.0,2
...,...,...,...,...,...,...,...,...,...,...
997,Russell,Male,5/20/2013,12:39 PM,96914,1.421,False,Product,1.0,7
998,Larry,Male,4/20/2013,4:45 PM,60500,11.985,False,Business Development,12.0,5
999,Albert,Male,5/15/2012,6:24 PM,129949,10.169,True,Sales,10.0,2
1000,Douglas,Male,8/6/1993,12:42 PM,97308,6.945,True,Marketing,7.0,9
1001,Thomas,Male,3/31/1996,6:53 AM,61933,4.170,True,NaN,4.0,9

In [59]:
df4 = df.drop(['First_Name'],axis=1) #dropping columns
df4

,Gender,Start_Date,Last_Login_Time,Salary,Bonus,Senior_Management,Team,Bonus2,random
0,Male,8/6/1993,12:42 PM,97308,6.945,True,Marketing,7.0,9
1,Male,3/31/1996,6:53 AM,61933,4.170,True,NaN,4.0,9
2,Female,4/23/1993,11:17 AM,130590,11.858,False,Finance,12.0,6
3,Male,3/4/2005,1:00 PM,138705,9.340,True,Finance,9.0,7
4,Male,1/24/1998,4:47 PM,101004,1.389,True,Client Services,1.0,2
...,...,...,...,...,...,...,...,...,...
995,NaN,11/23/2014,6:09 AM,132483,16.655,False,Distribution,17.0,3
996,Male,1/31/1984,6:30 AM,42392,19.675,False,Finance,20.0,6
997,Male,5/20/2013,12:39 PM,96914,1.421,False,Product,1.0,7
998,Male,4/20/2013,4:45 PM,60500,11.985,False,Business Development,12.0,5
999,Male,5/15/2012,6:24 PM,129949,10.169,True,Sales,10.0,2

In [60]:
df.drop(range(5),axis=0) #dropping rows

,First_Name,Gender,Start_Date,Last_Login_Time,Salary,Bonus,Senior_Management,Team,Bonus2,random
5,Dennis,Male,4/18/1987,1:35 AM,115163,10.125,False,Legal,10.0,7
6,Ruby,Female,8/17/1987,4:20 PM,65476,10.012,True,Product,10.0,1
7,NaN,Female,7/20/2015,10:43 AM,45906,11.598,NaN,Finance,12.0,7
8,Angela,Female,11/22/2005,6:29 AM,95570,18.523,True,Engineering,19.0,0
9,Frances,Female,8/8/2002,6:51 AM,139852,7.524,True,Business Development,8.0,2
...,...,...,...,...,...,...,...,...,...,...
995,Henry,NaN,11/23/2014,6:09 AM,132483,16.655,False,Distribution,17.0,3
996,Phillip,Male,1/31/1984,6:30 AM,42392,19.675,False,Finance,20.0,6
997,Russell,Male,5/20/2013,12:39 PM,96914,1.421,False,Product,1.0,7
998,Larry,Male,4/20/2013,4:45 PM,60500,11.985,False,Business Development,12.0,5
999,Albert,Male,5/15/2012,6:24 PM,129949,10.169,True,Sales,10.0,2

In [61]:
df = pd.read_csv('employees.csv')

In [62]:
df.Gender.value_counts()

Gender
Female    431
Male      424
Name: count, dtype: int64

In [63]:
df.Gender.isna().sum()

145

In [65]:
df['Gender2'] = pd.Categorical(df.Gender)
df.head()

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team,Gender2
0,Douglas,Male,8/6/1993,12:42 PM,97308,6.945,True,Marketing,Male
1,Thomas,Male,3/31/1996,6:53 AM,61933,4.170,True,NaN,Male
2,Maria,Female,4/23/1993,11:17 AM,130590,11.858,False,Finance,Female
3,Jerry,Male,3/4/2005,1:00 PM,138705,9.340,True,Finance,Male
4,Larry,Male,1/24/1998,4:47 PM,101004,1.389,True,Client Services,Male

In [66]:
df.memory_usage()

Index                 132
First Name           8000
Gender               8000
Start Date           8000
Last Login Time      8000
Salary               8000
Bonus %              8000
Senior Management    8000
Team                 8000
Gender2              1124
dtype: int64

In [67]:
import random

In [70]:
df['Score'] = pd.Series(random.choices(['Very Low','Low','Medium','High','Very High'],k=1000))
df.head()

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team,Gender2,Score
0,Douglas,Male,8/6/1993,12:42 PM,97308,6.945,True,Marketing,Male,Very High
1,Thomas,Male,3/31/1996,6:53 AM,61933,4.170,True,NaN,Male,Medium
2,Maria,Female,4/23/1993,11:17 AM,130590,11.858,False,Finance,Female,Low
3,Jerry,Male,3/4/2005,1:00 PM,138705,9.340,True,Finance,Male,Medium
4,Larry,Male,1/24/1998,4:47 PM,101004,1.389,True,Client Services,Male,High

In [74]:
df['Score2'] = pd.Categorical(df.Score,categories=['Very Low','Low','Medium','High','Very High'],ordered=True) #hierarchy

In [75]:
df.Score2 > 'Medium'

0       True
1      False
2      False
3      False
4       True
       ...
995    False
996    False
997    False
998    False
999     True
Name: Score2, Length: 1000, dtype: bool

In [76]:
sum(df.Score2>'Medium')

403

In [77]:
df.Salary.min()

35013

In [78]:
df.Salary.max()

149908

In [79]:
pd.cut(df.Salary, bins = [35000,50000,75000,100000,125000,150000],
                  labels=['Very Low','Low','Medium','High','Very High']) #classifying salaries

0         Medium
1            Low
2      Very High
3      Very High
4           High
         ...
995    Very High
996     Very Low
997       Medium
998          Low
999    Very High
Name: Salary, Length: 1000, dtype: category
Categories (5, object): ['Very Low' < 'Low' < 'Medium' < 'High' < 'Very High']